spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      ddl-auto: update
